### PR TITLE
Added support for Amazon Linux AMI 2016.03

### PR DESCRIPTION
**Pull request by negito6**
A new version of Amazon Linux AMI has been released.
https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/

This commit contains support for platform_versions of 2016.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @negito6

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by minamijoyo** [comment]
+1

**Comment by tas50** [comment]
Thanks for this addition.  I saw #10 first so I merged that one.

**Comment by negito6** [comment]
@tas50 No Problem! Thank you for your comment and merge #10 :smile:

**Pull request closed without merging**
